csharp provider
railwayapp/nixpacks pull request #107
Opened 2022-05-11 23:12 UTC by nebulatgs

add support for simple (non solution) csharp projects

2022-05-12 03:36 UTC, devtomio requested changes

2022-05-12 03:36 UTC, devtomio commented on src/providers/csharp.rs
> +        ))))
```suggestion
        Ok(Some(BuildPhase::new(format!(
            "dotnet publish --no-restore -c Release -o {}",
            ARTIFACT_DIR
        ))))
```

other `format!` calls in nixpacks uses this syntax

2022-05-12 03:36 UTC, devtomio commented on src/providers/csharp.rs
> +        ))))
```suggestion
        Ok(Some(StartPhase::new(format!(
            "./{}/{}",
            ARTIFACT_DIR,
            project_name
        ))))
```

same reason

2022-05-12 20:28 UTC, Milo123459 commented
Is the example program supposed to be this big? The ones for other languages aren't.

2022-05-12 20:58 UTC, coffee-cup commented on src/providers/csharp.rs
> +            ("PORT".to_string(), "3000".to_string()),
I don't think we should be setting the `PORT` here. It should be able to be dynamic

2022-05-17 05:14 UTC, coffee-cup approved these changes
Few minor comments but looks good! Can merge after addressed + lints

2022-05-17 05:14 UTC, coffee-cup commented on src/providers/csharp.rs
> +            .unwrap()
Instead of unwrapping can you `?` instead. That way the error bubbles up.

2022-05-17 05:14 UTC, coffee-cup commented on examples/csharp-cli/Program.cs
> +Console.WriteLine("Hello, World!");
nit: Change to "Hello world from C#" to keep consistent with other languages

2022-05-30 18:42 UTC, coffee-cup commented
Gentle poke on this PR. Would love to get it merged.

2022-05-30 21:20 UTC, JakeCooper commented
I would love a dotNET example with this. 

C# server serving hello world or something.

If you wanna get it working with dotNET and the tests passing happy to throw a $100 bounty on this one as well

2022-05-30 21:22 UTC, coffee-cup commented on tests/docker_run_tests.rs
> +    assert!(output.contains("Hello, World!"));
I think this should be
```suggestion
    assert!(output.contains("Hello world from C#"));
```

2022-06-02 13:10 UTC, nebulatgs commented
> I would love a dotNET example with this. 
> 
> 
> 
> C# server serving hello world or something.
> 
> 
> 
> If you wanna get it working with dotNET and the tests passing happy to throw a $100 bounty on this one as well
> 
> 
> 
> EDIT: I can't tell if this is a dotNET project or w/e. Neither coffee-cup nor I have written a lick of C# lmao

yup this is dotnet core

2022-06-02 23:07 UTC, merged