Add docs for pnpm and yarn 2+
railwayapp/nixpacks pull request #125
Opened 2022-05-14 11:36 UTC by wyzlle

Updated docs for node provider.

2022-05-14 17:40 UTC, Milo123459 commented on docs/node.md
> +For all three NPM, Yarn and PNPM providers, the following environment variables are set.
```suggestion
The NPM, Yarn and PNPM providers all have the following environment variables set:
```

2022-05-14 17:40 UTC, Milo123459 commented on docs/node.md
> +If lockfile is found in source code
```suggestion
If a lockfile is found in the source code
```

2022-05-14 17:40 UTC, Milo123459 commented on docs/node.md
> +If lockfile isn't found in source code
````suggestion
If a lockfile isn't found in the source code
```

2022-05-14 17:41 UTC, Milo123459 commented on docs/node.md
> +npm start
Should be reverted as your PR changing this was closed.
```suggestion
npm run start
```

2022-05-14 20:28 UTC, Milo123459 approved these changes

2022-05-16 03:48 UTC, devtomio requested changes

2022-05-16 03:48 UTC, devtomio commented on docs/node.md
> +For Yarn 1
```suggestion
For [Yarn 1](https://classic.yarnpkg.com/lang/en/)
```

2022-05-16 03:48 UTC, devtomio commented on docs/node.md
> +For Yarn 2+
```suggestion
For [Yarn 2+](https://yarnpkg.com/)
```

2022-05-16 16:14 UTC, merged