Match both zip and tar.gz in release pipeline
railwayapp/nixpacks pull request #134
Opened 2022-05-15 19:36 UTC by nebulatgs

Fixes #131

2022-05-15 21:18 UTC, Milo123459 approved these changes

2022-05-18 06:11 UTC, devtomio requested changes

2022-05-18 06:11 UTC, devtomio commented on .github/workflows/release.yml
> +        files: nixpacks-${{ needs.create-release.outputs.nixpacks_version }}-${{ matrix.target }}.{zip,tar.gz}
```suggestion
        files: nixpacks-${{ needs.create-release.outputs.nixpacks_version }}-${{ matrix.target }}*
```

2022-05-18 06:11 UTC, devtomio commented on .github/workflows/release.yml
> +        files: nixpacks-${{ needs.create-release.outputs.nixpacks_version }}-${{ matrix.target }}.{zip,tar.gz}
I think its better to use a wildcard to fix https://github.com/railwayapp/nixpacks/pull/134#issuecomment-1127878630

2022-05-20 17:21 UTC, devtomio approved these changes

2022-05-20 22:45 UTC, coffee-cup approved these changes

2022-05-20 22:45 UTC, merged