fix: allow targets without a options attribute
railwayapp/nixpacks pull request #552
Opened 2022-09-14 21:56 UTC by FinnDore

This pr makes it so the `options` attribute does not need to be present on a  `target` within a `project.json` ( NX )

This originally came from [here](https://discord.com/channels/713503345364697088/1009464427185193070/1017567215140216865) where Jaka had a valid project.json without a options attribute in his build target, adding an empty one like `"options": {}` satisfied NIXPACKS.

[I seem to be unable to run the NX tests on my branch neither main](https://app.warp.dev/block/ECEJtCOWwXpktlCvnOZO01). So ill look into that tomorrow afternoon if i cant find the cause asap ( Sleep is vital :))

2022-09-14 22:05 UTC, FinnDore commented
Need to swap out the builder for something that does not require a options attribute -_-

2022-09-15 22:24 UTC, FinnDore commented
Just pushed an astro project without the options attribute. Please not ive used a dumby start command as astro build a static site with this nx extension and as we dont care about the start command in this test its fine.

thanks to whoever has run ci. quick reaction times :)

2022-09-15 22:27 UTC, FinnDore commented
Interesting ive broken some of the other NX tests. ill try get the working on my mac, its an m1 so i am having issues with that atm

2022-09-15 22:53 UTC, FinnDore commented
Should be fixed. Caused by sleep deprivation 🙄

2022-09-15 23:20 UTC, FinnDore commented
Looks like its happy. Just talking to neb about some unwraps i noticed. Happy to fix them in this PR or create another just dont want to be spammy with PR's  https://discord.com/channels/713503345364697088/960605685920452669/1020105591210922055

2022-09-17 16:24 UTC, Milo123459 requested changes

2022-09-17 16:24 UTC, Milo123459 commented on src/providers/node/nx.rs
> +    pub options: Option<Options>,
Could we rename the `Options` struct to be something like `NxDevOptions`?

2022-09-17 20:27 UTC, FinnDore commented
Good idea. renamed!
Also spoke to neb and he suggested that a new pr should be made to fix the unwraps in the node provider.

2022-09-18 11:05 UTC, Milo123459 approved these changes

2022-09-18 11:25 UTC, merged